language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t vendelserkedocker/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true vendelserkedocker/docker-react npm run test